#!/bin/bash

log() {
    echo "$(date): $1"
}

update() {
    log "Updating system"
    sudo apt-get update -qq
}

upgrade() {
    log "Upgrading packages"
    sudo apt-get upgrade -yqq
}

ensure_packages() {
    if [ ! -z "$1" ]
    then
        log "Installing packages: ($1)"
        sudo apt-get install -yq $1
    fi
}

require_root() {
    # if [[ $EUID -ne 0 ]]; then
    # log "This script must be run as root" 
    # exit 1
    # fi
    sudo -v
}

deb_install() {
    dpkg -i $1
}

apt_install() {
    sudo apt-get install -yq $1
}
