#!/bin/bash

log() {
    require_root
    echo "$(date): $1"
}

apt_update() {
    require_root
    log "Updating system"
    sudo apt-get update -qq
}

apt_upgrade() {
    require_root
    log "Upgrading packages"
    sudo apt-get upgrade -yqq
}

ensure_packages() {
    require_root
    if [ ! -z "$1" ]
    then
        log "Installing packages: ($1)"
        sudo apt-get install -yqq $1
    fi
}

ensure_snaps() {
    require_root
    if [ ! -z "$1" ]
    then
        log "Installing snaps: ($1)"
        sudo snap install $1 > /dev/null 2>&1
    fi
}

ensure_classic_snaps() {
    require_root
    if [ ! -z "$1" ]
    then
        log "Installing classic snaps: ($1)"
        for snap in $1; do
            sudo snap install --classic $snap > /dev/null 2>&1
        done
    fi
}

require_root() {
    # if [[ $EUID -ne 0 ]]; then
    # log "This script must be run as root" 
    # exit 1
    # fi
    sudo -v
}

deb_install() {
    require_root
    sudo dpkg -i $1
}

add_repo() {
    require_root
    sudo apt-add-repository -y $1
}