#!/bin/bash

log() {
    echo "$(date): $1"
}

update() {
    log "Updating system"
    apt-get update -qq
}

upgrade() {
    log "Upgrading packages"
    apt-get upgrade -yqq
}

ensure_packages() {
    if [ ! -z "$1" ]
    then
        log "Installing packages: ($1)"
        apt-get install -yq $1
    fi
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
    log "This script must be run as root" 
    exit 1
    fi
}

deb_install() {
    dpkg -i $1
}

apt_install() {
    apt-get install -yq $1
}
